"""Checkpoint 3 — the passwordless-``sudo`` opt-in.

This is the most dangerous thing setup can offer, so it is the narrowest. The
drop-in it generates:

* names **one account**, never ``%sudo`` or any other group — a group-wide
  ``NOPASSWD`` would silently cover every future administrator;
* is mode ``0440`` in ``/etc/sudoers.d/``, the only mode ``sudo`` will read;
* is refused unless it validates. On a host with ``visudo`` the drop-in is
  checked with ``visudo -cf``; where ``visudo`` is absent that arm reports
  **unavailable** rather than passing, because an unrun check is not a pass.

The account name is treated as hostile input throughout. It is matched against
a conservative pattern before it is ever interpolated, so no name can close the
rule and open another.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

#: Deliberately narrower than Debian's ``NAME_REGEX``: setup writes a sudoers
#: fragment, and a name that is merely a legal login is not automatically a
#: safe token in that grammar.
ACCOUNT_PATTERN = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")

#: Group references are refused outright rather than validated.
FORBIDDEN_PREFIXES = ("%", "+", "#")

DROPIN_MODE = 0o440

VALIDATION_PASS = "pass"
VALIDATION_FAIL = "fail"
VALIDATION_UNAVAILABLE = "unavailable"


class SudoersRefusal(ValueError):
    """The requested fragment will not be generated."""


@dataclass(frozen=True)
class SudoersDropin:
    account: str
    filename: str
    content: str

    @property
    def mode(self) -> int:
        return DROPIN_MODE


def build_dropin(account: str) -> SudoersDropin:
    """Generate the one-account drop-in, or refuse."""

    if not isinstance(account, str) or not account:
        raise SudoersRefusal("no account was selected")
    if account.startswith(FORBIDDEN_PREFIXES):
        raise SudoersRefusal(
            f"{account!r} names a group or netgroup; setup grants NOPASSWD to one account only"
        )
    if not ACCOUNT_PATTERN.match(account):
        raise SudoersRefusal(f"{account!r} is not a name setup will write into a sudoers fragment")

    content = (
        "# Generated by plebian-os-setup. One account, chosen explicitly at first login.\n"
        "# Remove this file to require a password again.\n"
        f"{account} ALL=(ALL:ALL) NOPASSWD: ALL\n"
    )
    return SudoersDropin(
        account=account,
        filename=f"90-plebian-os-setup-{account}",
        content=content,
    )


def contains_group_wide_nopasswd(content: str) -> bool:
    """True when a fragment would grant ``NOPASSWD`` to a group."""

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "NOPASSWD" not in stripped:
            continue
        subject = stripped.split(None, 1)[0]
        if subject.startswith(FORBIDDEN_PREFIXES):
            return True
    return False


def validate(dropin: SudoersDropin, directory: Path) -> tuple[str, str]:
    """Validate a fragment, returning ``(result, detail)``.

    ``result`` is ``pass``, ``fail`` or ``unavailable``. There is no fourth
    value, and ``unavailable`` is not treated as success anywhere.
    """

    if contains_group_wide_nopasswd(dropin.content):
        return VALIDATION_FAIL, "fragment grants NOPASSWD to a group"

    visudo = shutil.which("visudo")
    if visudo is None:
        return (
            VALIDATION_UNAVAILABLE,
            "visudo is not installed on this host; the fragment was not machine-checked",
        )

    directory.mkdir(parents=True, exist_ok=True)
    path = directory / dropin.filename
    path.write_text(dropin.content, encoding="utf-8")
    path.chmod(DROPIN_MODE)
    completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [visudo, "-cf", str(path)],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        shell=False,
        timeout=15,
    )
    if completed.returncode == 0:
        return VALIDATION_PASS, "visudo -cf accepted the fragment"
    return VALIDATION_FAIL, completed.stdout.decode("utf-8", "replace").strip()[:512]
